complete block list with loomSDK
loomnetwork/vue-block-explorer pull request #10
Opened 2018-06-21 03:04 UTC by Jangmingjin

2018-06-21 06:24 UTC, enlight requested changes
Run `yarn format` to get rid of irrelevant code style changes.

2018-06-21 11:25 UTC, enlight commented on src/blockchain.ts
> +      console.log('set Server Url')
Is this needed?

2018-06-21 11:25 UTC, enlight commented on src/components/card.ts
> +    console.log('The prop: ', this.elementId)
And this?

2018-06-21 11:25 UTC, enlight commented on src/components/nav.ts
> +    console.log('Nav is mounted')
Or this?

2018-06-22 09:18 UTC, enlight commented
I just noticed this PR isn't against `master`, did you mean to merge it into the `redesign` branch?

2018-06-22 09:21 UTC, Jangmingjin commented
Yeah. It's based on redesign branch and I thought it should be merged into redesign..

2018-06-22 09:24 UTC, merged